apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: planet-hunter-fleet
spec:
  replicas: 3
  template:
    spec:
      health:
        initialDelaySeconds: 120
        periodSeconds: 10
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
      template:
        spec:
          players:
            initialCapacity: 4
          nodeSelector:
            node-type: workers
          containers:
            - name: unity-simple-server
              # image: AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/planet-hunter-server:0.4
              image: 192.168.1.17:5000/planet-hunter-server:0.4
              imagePullPolicy: IfNotPresent
          # imagePullSecrets:
          #   - name: ecr-creds
          resources:
            requests:
              memory: 128Mi
              cpu: 128m
            limits:
              memory: 256Mi
              cpu: 128m

