apiVersion: agones.dev/v1
kind: GameServer
metadata:
  generateName: planet-hunter-server-
spec:
  health:
    initialDelaySeconds: 120
    periodSeconds: 10
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7777
  template:
    spec:
      containers:
        - name: planet-hunter-server
          image: 192.168.1.17:5000/planet-hunter-server:0.4
          imagePullPolicy: Always
      resources:
        requests:
          memory: 128Mi
          cpu: 128m
        limits:
          memory: 256Mi
          cpu: 128m
