#cloud-config
package_update: true
packages:
  - git
  - curl
  - unzip
write_files:
  - path: /tmp/setup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      
      apt-get update
      
      ################
      # allocate 2GB swapfile for stability
      echo "Allocating swapfile..."
      fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab

      ################
      echo "Installing ArgoCD CLI..."
      mkdir -p /usr/local/bin
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v3.3.9/argocd-linux-amd64
      chmod +x /usr/local/bin/argocd

      ################
      echo "Installing k3s..."
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      echo "Waiting for K3s..."
      until [ -f /etc/rancher/k3s/k3s.yaml ]; do sleep 2; done

      ################
      echo "Installing ArgoCD..."
      kubectl create namespace argocd
      kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.9/manifests/install.yaml
      
      ################
      echo "Installing AWS CLI..."
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install
      rm -rf awscliv2.zip awsi

      # test token
      TEST_TOKEN=$(aws ssm get-parameter --name "/github/test-token" --with-decryption --query "Parameter.Value" --output text)
      echo $TEST_TOKEN

      ################
      echo "Cloud-init finished at $(date)"

runcmd:
  - bash /tmp/setup.sh

