---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: planet-hunter-fleet-autoscaler
spec:
  fleetName: planet-hunter-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 6
      minReplicas: 12
      maxReplicas: 24
