---
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: planet-hunter-fleet
spec:
  replicas: 3
  template:
    spec:
      health:
        initialDelaySeconds: 120
        periodSeconds: 10
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
      players:
        initialCapacity: 4
      template:
        spec:
          nodeSelector:
            node-type: workers
          containers:
            - name: unity-simple-server
              image: {{ .Values.awsId }}.dkr.ecr.eu-west-1.amazonaws.com/planet-hunter-server:0.7
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: 200Mi
                  cpu: 30m
                limits:
                  memory: 300Mi
                  cpu: 100m

