# Replace <your-email> and <your_token> with actual values
# This config should ideally be placed in: /var/lib/rancher/k3s/server/manifests
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      path: /var/lib/rancher/k3s/storage/traefik
      size: 128Mi
    additionalArguments:
      - "--log.level=DEBUG"
      - "--certificatesresolvers.letsencrypt.acme.email=example@test.com"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=30"
    env:
      - name: CF_API_EMAIL
        value: example@test.com
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token-secret
            key: api-token
      - name: CF_ZONE_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token-secret
            key: api-token
